
# general settings
name: 201_ATD_SRx2_Infrared
model_type: ATDModel
scale: 2
num_gpu: 2
manual_seed: 0
# find_unused_parameters: True

# dataset and data loader settings
datasets:
  # train:
  #   name: 101ThermalTau2-S
  #   type: PairedImageDataset
  #   dataroot_gt: datasets/101ThermalTau2-S/train/HR
  #   dataroot_lq: datasets/101ThermalTau2-S/train/LR
  #   filename_tmpl: '{}'
  #   io_backend:
  #     type: disk
  train:
    name: 101ThermalTau2-S
    type: PairedImageDataset
    dataroot_gt: datasets/101ThermalTau2-S/train/HR
    dataroot_lq: datasets/101ThermalTau2-S/train/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: True
    persistent_workers: True

  val_1:
    name: 101ThermalTau2-S
    type: PairedImageDataset
    dataroot_gt: datasets/101ThermalTau2-S/test/HR
    dataroot_lq: datasets/101ThermalTau2-S/test/LR
    io_backend:
      type: disk

  # val_1:
  #   name: 101ThermalTau2-S
  #   type: PairedImageDataset
  #   dataroot_gt: datasets/101ThermalTau2-S/test/HR
  #   dataroot_lq: datasets/101ThermalTau2-S/test/LR
  #   io_backend:
  #     type: disk

# network structures
network_g:
  type: ATD
  upscale: 2
  in_chans: 3
  img_size: 64
  embed_dim: 210
  depths: [6, 6, 6, 6, 6, 6,]
  num_heads: [6, 6, 6, 6, 6, 6,]
  window_size: 16
  category_size: 256
  num_tokens: 128
  reducted_dim: 20
  convffn_kernel_size: 5
  img_range: 1.
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
  use_checkpoint: false

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.9]

  scheduler:
    type: MultiStepLR
    milestones: [250000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: 10000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: 20000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: yes

    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 2
      test_y_channel: yes

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
